name: Build and deploy pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
  # Allow to trigger from outside
  repository_dispatch:
    types: ["deploy"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Checkout PopTracker
        uses: actions/checkout@v3
        with:
          repository: black-sliver/PopTracker
          path: .poptracker
          submodules: true
      - name: Copy from PopTracker to pages
        run: |
          cp -R .poptracker/schema schema
          cp -R .poptracker/doc doc
      - name: Create schema indices
        run: |
          cd schema
          for d in */; do \
            echo -e "# ${d%/} Schema\n" > $d/index.md; \
            cd "$d"; \
            for f in *; do \
                [ "$f" != "index.md" ] && echo "* [$f]($f)" >> index.md; \
            done; \
            for e in */; do \
              if [ -d "$e" ]; then
                echo -e "# ${d%/} ${e%/} Schema\n" > $e/index.md; \
                cd "$e"
                for f in *; do \
                  [ "$f" != "index.md" ] && echo "* [$f]($f)" >> index.md; \
                done; \
                cd ..; \
              fi; \
            done; \
            cd ..; \
          done
          cd ..
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
